version: "3"
services:
  sub1:
    stdin_open: true
    build: ./sub1
    ports: 
      - "3000:3000"
    depends_on:
      - socket-server-3
    networks:
      - mern-app
  sub2:
    stdin_open: true
    build: ./sub2
    ports: 
      - "3001:3001"
    depends_on:
      - socket-server-3
    networks:
      - mern-app
  api-server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  socket-server-1:
    build: ./socket_server_1
    ports:
      - "7001:7001"
    networks:
      - mern-app
    depends_on:
      - api-server
  socket-server-2:
    build: ./socket_server_2
    ports:
      - "7002:7002"
    networks:
      - mern-app
    depends_on:
      - socket-server-1
  socket-server-4:
    build: ./socket_server_4
    ports:
      - "7004:7004"
    networks:
      - mern-app
    depends_on:
      - socket-server-1
  socket-server-3:
    build: ./socket_server_3
    ports:
      - "7003:7003"
    networks:
      - mern-app
    depends_on:
      - socket-server-2
      - socket-server-4
  pub1:
    build: ./pub1
    ports:
      - "7005:7005"
    networks:
      - mern-app
    depends_on:
      - socket-server-3
  pub2:
    build: ./pub2
    ports:
      - "7006:7006"
    networks:
      - mern-app
    depends_on:
      - socket-server-3
  pub3:
    build: ./pub3
    ports:
      - "7007:7007"
    networks:
      - mern-app
    depends_on:
      - socket-server-3
  pub4:
    build: ./pub4
    ports:
      - "7008:7008"
    networks:
      - mern-app
    depends_on:
      - socket-server-3 
  


networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
